os: linux
dist: xenial
language: python
sudo: false
python:
  - "3.6"
  - "3.7"

install:
  - pip install pytest
  - pip install .

script:
  - cd sample
  - python demo.py
  - python short.py
  - pytest tests/
