os: linux
dist: xenial
language: python
sudo: true
python:
  - "3.6"
  - "3.7"

install:
  - apt-get -y install tesseract-ocr tesseract-ocr-chi-sim libtesseract-dev libleptonica-dev pkg-config
  - pip install pytest
  - pip install findit-client
  - pip install tesserocr
  - pip install .

script:
  - cd sample
  - python demo.py
  - python short.py
  - cd ..
  - pytest tests/
